name: Generate snake animation

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Generate snake.svg
        uses: Platane/snk@master
        with:
          github_user_name: kikemal
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
          
      - name: Deploy to output branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: output
          commit_message: "Generate snake animation"
          force_orphan: true
